# Generated by Django 2.1 on 2018-08-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_comment_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelist',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attendancelist',
            name='person',
        ),
        migrations.RemoveField(
            model_name='chosengroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='chosengroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='event',
            name='person_in_charge',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='person',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='query',
        ),
        migrations.RemoveField(
            model_name='servicetool',
            name='service',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='attendanceList',
        ),
        migrations.DeleteModel(
            name='chosenGroup',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Responses',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='serviceTool',
        ),
        migrations.DeleteModel(
            name='signUp',
        ),
    ]
