# Generated by Django 2.1 on 2018-08-11 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_auto_20180811_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Event'),
        ),
    ]
