# Generated by Django 2.1 on 2018-08-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_auto_20180811_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Grouped',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='person',
        ),
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.CharField(max_length=30),
        ),
    ]
