# Generated by Django 2.1 on 2018-08-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_servicetool_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
