# Generated by Django 2.1 on 2018-08-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_auto_20180813_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
