# Generated by Django 2.1 on 2018-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0021_auto_20180814_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
        migrations.AddField(
            model_name='signup',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='signup',
            name='agree_with_terms_and_conditions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=' ', max_length=1),
        ),
        migrations.AddField(
            model_name='signup',
            name='nationality',
            field=models.CharField(choices=[('uganda', 'Ugandan'), ('kenya', 'Kenyan'), ('tanzania', 'Tanzanian'), ('rwanda', 'Rwandese'), ('sudan', 'Sudanese'), ('india', 'Indian'), ('somalia', 'Somalese'), ('usa', 'American'), ('britain', 'British'), ('france', 'French'), ('russia', 'Russian'), ('congo', 'Congolese'), ('nigeria', 'Nigerian'), ('germany', 'German'), ('sa', 'South African')], default='uganda', max_length=20),
        ),
        migrations.AddField(
            model_name='signup',
            name='occupation',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='signup',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'Single'), ('In a Relationship', (('dating', 'Dating'), ('engaged', 'Engaged'), ('married', 'Married')))], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='signup',
            name='terms_and_conditions',
            field=models.TextField(default='1.We are a strictly anglican church group'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='profile',
            field=models.TextField(default='Tell us about yourself'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='tel_number',
            field=models.IntegerField(default=256),
        ),
    ]
