# Generated by Django 2.1 on 2018-08-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0022_auto_20180814_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='full_name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
