# Generated by Django 2.1 on 2018-08-16 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0024_auto_20180816_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendanceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='chosenGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('person', models.CharField(max_length=30)),
                ('query', models.TextField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='docs')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('person_in_charge', models.CharField(max_length=30)),
                ('event', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('google_maps', models.ImageField(upload_to='maps')),
            ],
        ),
        migrations.CreateModel(
            name='Grouped',
            fields=[
                ('group', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='pics')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Grouped')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=' ', max_length=30)),
                ('answer', models.TextField(blank=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='serviceTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('item', models.URLField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Service')),
            ],
        ),
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('full_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=' ', max_length=1)),
                ('nationality', models.CharField(choices=[('uganda', 'Ugandan'), ('kenya', 'Kenyan'), ('tanzania', 'Tanzanian'), ('rwanda', 'Rwandese'), ('sudan', 'Sudanese'), ('india', 'Indian'), ('somalia', 'Somalese'), ('usa', 'American'), ('britain', 'British'), ('france', 'French'), ('russia', 'Russian'), ('congo', 'Congolese'), ('nigeria', 'Nigerian'), ('germany', 'German'), ('sa', 'South African')], default='uganda', max_length=20)),
                ('address', models.TextField(default=' ')),
                ('relationship_status', models.CharField(choices=[('single', 'Single'), ('In a Relationship', (('dating', 'Dating'), ('engaged', 'Engaged'), ('married', 'Married')))], default='single', max_length=10)),
                ('profile', models.TextField(default='Tell us about yourself')),
                ('tel_number', models.IntegerField(default=256)),
                ('occupation', models.CharField(default=' ', max_length=20)),
                ('profile_picture', models.ImageField(upload_to='profile_pics')),
                ('terms_and_conditions', models.TextField(default='1.We are a strictly anglican church group')),
                ('agree_with_terms_and_conditions', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='vids')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Event'),
        ),
        migrations.AddField(
            model_name='chosengroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.signUp'),
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Event'),
        ),
    ]
