# Generated by Django 2.1 on 2018-08-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0027_auto_20180817_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='pics')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='church.Event')),
            ],
        ),
    ]
