# Generated by Django 2.1 on 2018-08-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0028_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
