# Generated by Django 2.1 on 2018-08-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0033_pledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='nationality',
            field=models.CharField(choices=[('Ugandan', 'Ugandan'), ('Kenyan', 'Kenyan'), ('Tanzanian', 'Tanzanian'), ('Rwandese', 'Rwandese'), ('Sudanese', 'Sudanese'), ('Indian', 'Indian'), ('Somalese', 'Somalese'), ('American', 'American'), ('British', 'British'), ('French', 'French'), ('Russian', 'Russian'), ('Congolese', 'Congolese'), ('Nigerian', 'Nigerian'), ('German', 'German'), ('South African', 'South African')], default='uganda', max_length=20),
        ),
    ]
