# Generated by Django 2.1 on 2018-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0034_auto_20180831_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
