# Generated by Django 2.1 on 2018-09-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0035_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('title', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='newsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.New')),
            ],
        ),
    ]
