# Generated by Django 2.1 on 2018-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0036_new_newsimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='terms_and_conditions',
            field=models.TextField(default='1.We are a strictly anglican church group', editable=False),
        ),
    ]
